### ISSUE TITLE
Source Go from stable Alpine repo after 1.5 is available there

### ISSUE THREAD

**Issue by tamas-molnar** [Financial-Times/coco-mongodb-backup#4]
Go 1.5 is not available from the stable alpine repo yet: http://dl-4.alpinelinux.org/alpine/v3.2/main
We are getting it from the `edge` repo: http://dl-4.alpinelinux.org/alpine/edge/community

Once Go 1.5 is available in the stable repo, adjust the docker file to get Go from there.

**Comment by kghatton** [comment]
See https://github.com/Financial-Times/coco-mongodb-backup/pull/10
